### ISSUE TITLE
update circleci to pass config file location via environment variable.

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#299]
see if updating ```.circleci/config.yml``` to:

```
build:
    docker:
      - image: circleci/python:3.6.2
      environment:
        POSEIDON_CONFIG: /tmp/poseidonWork/config/poseidon.config
    working_directory: /tmp/poseidonWork
    steps:
      - checkout
```
by adding 
```
      environment:
        POSEIDON_CONFIG: /tmp/poseidonWork/config/poseidon.config
```
below the ```- image``` line fixes the build.
