### ISSUE TITLE
setting mirror setting to incorrect port (setting is reversed)

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#474]
These lines need to be updated:

https://github.com/CyberReboot/poseidon/blob/master/poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/faucet/parser.py#L92

https://github.com/CyberReboot/poseidon/blob/master/poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/faucet/parser.py#L94

**Comment by alshaboti** [comment]
Yes, I was about to report this. 
I am using mirror port number 3 
```
controller_mirror_ports={"openwrt":3}
```
But Poseidon configures Faucet to mirror port 3 traffic to port 1. 
The correct is the opposit!
```
dps:
  openwrt:
    dp_id: 0x14cc20be86a9
    hardware: Open vSwitch
    interfaces:
      1:
        native_vlan: demo
      2:
        native_vlan: demo
      3:
        mirror: 1
        native_vlan: mirror
    proactive_learn: true
vlans:
  demo:
    vid: 300
  mirror:
    max_hosts: 0
    vid: 101
```
